install! "cocoapods", :integrate_targets => false

platform :ios, '8'

pods = [
  'AFNetworking',        # Git
  'VeriJSON',            # Mercurial
  'clipper',             # Subversion
  'GoogleMaps',          # HTTPS
  # TODO no public bazaar repos? :/
]

target "Test" do
  cache_dir = File.expand_path('~/Library/Caches/CocoaPods/Pods/Release')
  pods.each do |name|
    # Ensure the downloaders are actually tested.
    FileUtils.rm_rf(File.join(cache_dir, name))
    pod(name)
  end
end
