platform :osx

# TODO inhibiting warnings (when they’re not harmfule) while working on the application.

# Has 3 warnings about deprecated -[NSImage setFlipped:] API
pod 'Fragaria', :podspec => 'Fragaria.podspec.json', :inhibit_warnings => true
# Has 6 warnings about integer precision loss.
pod 'ANSIEscapeHelper', :podspec => 'ANSIEscapeHelper.podspec', :inhibit_warnings => true

post_install do |installer|
  # We don't need all of Fragaria's syntax definitions.
  script = installer.libraries.first.copy_resources_script_path
  content = script.read
  content = content.sub('install_resource "Fragaria/Syntax Definitions"', '')
  content = content.sub('install_resource "Fragaria/SyntaxDefinitions.plist"', '')
  script.open('w') { |f| f << content }
end
