#import <Foundation/Foundation.h>

@class CPUserProject, CPXcodeProject, CPCocoaPodsTarget;

/// Converts from a NSDictionary hash generated by RBObject+CocoaPods.rb + CPReflectionService -> Native classes for showing metadata

@interface CPXcodeInformationGenerator : NSObject

- (void)XcodeProjectMetadataFromUserProject:(CPUserProject * _Nonnull)project reply:(void (^ _Nonnull)(NSArray<CPXcodeProject *> * _Nonnull projects, NSArray<CPCocoaPodsTarget *> * _Nonnull targets, NSError * _Nullable error))reply;


@end
